### ISSUE TITLE
trailertbl function fails

### ISSUE THREAD

**Issue by costLAB** [cajoku/GCGRrepo#10]
selectcell is returning nothing

`
Function trailertbl(referRAN As Range, trailerRAN As Range) As Double
On Error GoTo e1

    Dim tVAL As Double
    Dim tNAME As String
    Dim tblRAN As Range
    Dim startcell As Range, headers As Range, cell As Range, selectcell As Range, attRAN As Range, attcell As Range
    Dim i As Integer
    
    tNAME = trailerRAN.Value
    Set tblRAN = Worksheets("Code").[\t_trailer]
    Set startcell = tblRAN.Cells(1, 1)
    Set headers = Union(startcell.Offset(0, 1), startcell.Offset(0, 2), startcell.Offset(0, 3))
    Set attRAN = Union(startcell.Offset(1, 0), startcell.Offset(2, 0), startcell.Offset(3, 0), startcell.Offset(4, 0), startcell.Offset(5, 0), startcell.Offset(6, 0), startcell.Offset(7, 0), startcell.Offset(8, 0))

    Set selectcell = headers.Find(What:=tNAME, MatchCase:=True) '!!!!!ERRORS OUT HERE
    Set attcell = attRAN.Find(referRAN.Value)
    
    trailertbl = Intersect(selectcell.EntireColumn, attcell.EntireRow).Value
    
Exit Function
`

**Comment by cajoku** [comment]
This is working fine on the current release of the template & code.
