### ISSUE TITLE
Staff Detail: changing a percent alloc on the grid auto populates other cells

### ISSUE THREAD

**Issue by costLAB** [cajoku/GCGRrepo#15]
Change this to the typical behavior the user expects, which is to except only the inputted cell value, and not recalc the others in the grid![2](https://user-images.githubusercontent.com/35744519/44222981-43b41400-a154-11e8-900a-a51629330ba6.gif)

**Comment by cajoku** [comment]
can change this setting to populates the empty months with 0%, but do we want this?
